### ISSUE TITLE
Add Archive Service to project

### ISSUE THREAD

**Issue by Yakov-Varnaev** [Yakov-Varnaev/BBQ-manager#1]
As [written in docs](https://github.com/Yakov-Varnaev/BBQ-manager/blob/main/docs/instances_UD.md), we cannot delete or update some instances, because it will affect historic data. So, ArchiveModelService needs to be added. It should work with any model, which has `archived` field.

```
class ArchiveModelServiceMixin:
    model = SomeModelHere

    def archive_and_update(self) -> Model: # returns updated instance
          '''
          Set flag archived to old instance to True and create new instance
          with updated data. If data is not changed raises an Exception.
          '''
          pass

    def archive(self) -> int:  # returns archived instance id
          '''
          Set flag archived to instance to True.
          '''
          pass
```

**Comment by max-bazarov** [comment]
Зачем нам поле model в классе, если этот класс может работать со многими моделями?

**Comment by max-bazarov** [comment]
Я с миксинами не работал, но много почитал про них. 
Мы от этого миксина сможем наследоваться во вью функции, чтобы использовать эти методы? Или будем наследовать модели от него?

**Comment by Yakov-Varnaev** [comment]
This is not mixin for model. This is mixin for Service. Actually, we do not need to make it as Mixin. We can make it as separate service object, which might be even better.

**Comment by Yakov-Varnaev** [comment]
[Here](http://mitchel.me/2017/django-service-objects/) you can read why service objects are needed. 

So. You need to implement hand-written service object, which will take instance as an argument and two methods: update and archive.

Forget about mixin, here is new version:)

```
class ArchiveService:

    class __init__(self, instance):
        self.instance = instance

    def update(self):
        '''
        Archive old and create new.
        '''

    def archive(self):
        '''
        Archive old.
        '''
```

[Here](https://github.com/Yakov-Varnaev/BBQ-manager/blob/main/docs/instances_UD.md) you can read a bit more.
