### ISSUE TITLE
Basic way to prevent duplication of base models

### ISSUE THREAD

**Issue by Yakov-Varnaev** [Yakov-Varnaev/BBQ-manager#41]
Create service which will prevent instance creation if instance with same data exists.

**Comment by Yakov-Varnaev** [comment]
For example user is trying to create new procedure with name, which already exists. Service should return existing instance instead of creating new one.

**Comment by max-bazarov** [comment]
@Yakov-Varnaev How will this service will be triggered? Give an example of usage, please
